function ListaArchivosM
figure('MenuBar','none',...
    'NumberTitle','off',...
    'Name','Lista Archivos',...
    'Position',[0 0 200 300]);
centerfig();

archivos_m = dir('*.m');
archivos_m = struct2cell(archivos_m);
uicontrol('style','listbox',...
    'String',archivos_m(1,:),...
    'Units','Normalized',...
    'Position',[0.02 0.02 0.96 0.96],...
    'Callback',@edit_call);

    function edit_call(src,~)
        str = get(src,'String');
        k = get(src,'Value');
        edit(str{k});
    end
end