function DemoEtiqueta
figure('MenuBar','None',...
    'NumberTitle','off',...
    'Name','Etiqueta',...
    'Position',[0 0 300 200]);
centerfig();

uicontrol('style','text',...
    'String','Mi etiqueta',...
    'Position',[50 90 200 20],...
    'FontSize',12,...
    'FontName','DejaVu Sans Mono');

end