function HolaMundo
figure('MenuBar','None',...
    'NumberTitle','off',...
    'Name','Hola Mundo');

uicontrol('style','push',...
    'String','Botón',...
    'Callback','msgbox(''Hola mundo'')');
end